### ISSUE TITLE
HI I FOUND YOU FROM INSTAGRAM 

### ISSUE THREAD

**Issue by cherrytheslime** [v801/portfolio#10]
I want your acc name cherryslime 
![8651E26F-498B-4D79-A766-729C92E12286](https://user-images.githubusercontent.com/67755587/86391583-e09bcf80-bc4e-11ea-97ce-314963c5041d.png)
![3BC284A1-BF82-4C72-BBD7-92C8F03A09C4](https://user-images.githubusercontent.com/67755587/86391590-e396c000-bc4e-11ea-97bf-95b9a8640a21.png)

**Comment by cherrytheslime** [comment]
I will buy your acc if needed I just want the @

**Comment by v801** [comment]
i do not use instragram and that is not my account, please dont open issues like this on github
